{{- if or .Values.autoscaling.enabled .Values.frontendAutoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "todo-app-4.fullname" . }}-frontend
  labels:
    {{- include "todo-app-4.labels" . | nindent 4 }}
    app: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "todo-app-4.fullname" . }}-frontend
  minReplicas: {{ if .Values.frontendAutoscaling.enabled }}{{ .Values.frontendAutoscaling.minReplicas }}{{ else }}{{ .Values.autoscaling.minReplicas }}{{ end }}
  maxReplicas: {{ if .Values.frontendAutoscaling.enabled }}{{ .Values.frontendAutoscaling.maxReplicas }}{{ else }}{{ .Values.autoscaling.maxReplicas }}{{ end }}
  metrics:
    {{- if or (and .Values.frontendAutoscaling.enabled .Values.frontendAutoscaling.targetCPUUtilizationPercentage) (and (not .Values.frontendAutoscaling.enabled) .Values.autoscaling.targetCPUUtilizationPercentage) }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ if .Values.frontendAutoscaling.enabled }}{{ .Values.frontendAutoscaling.targetCPUUtilizationPercentage }}{{ else }}{{ .Values.autoscaling.targetCPUUtilizationPercentage }}{{ end }}
    {{- end }}
    {{- if or (and .Values.frontendAutoscaling.enabled .Values.frontendAutoscaling.targetMemoryUtilizationPercentage) (and (not .Values.frontendAutoscaling.enabled) .Values.autoscaling.targetMemoryUtilizationPercentage) }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ if .Values.frontendAutoscaling.enabled }}{{ .Values.frontendAutoscaling.targetMemoryUtilizationPercentage }}{{ else }}{{ .Values.autoscaling.targetMemoryUtilizationPercentage }}{{ end }}
    {{- end }}
{{- end }}