apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: todo-app
type: Opaque
stringData:
  connection-string: "postgresql://neondb_owner:password@ep-sweet-feather-ahvkyo80-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"
