apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: notification-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "${KAFKA_BROKERS:localhost:9092}"
  - name: consumerGroup
    value: "notification-service"
  - name: publishTopic
    value: "notifications"
  - name: authType
    value: "none"
  - name: maxMessageBytes
    value: "1048576"
scopes:
- todo-backend
