apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "localhost:9092"
  - name: consumerGroup
    value: "todo-app"
  - name: publishTopic
    value: "todo-events"
  - name: authType
    value: "none"
  - name: maxMessageBytes
    value: "1048576"
